# Generated by Django 5.0.4 on 2024-05-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_employee_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': [('add_employee', 'Can add employees')]},
        ),
    ]
